name: CI

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v2

      - name: Set branch name
        run: echo >>$GITHUB_ENV BRANCH_NAME=${GITHUB_REF#refs/heads/}

      - name: Echo branch name
        run: echo ${BRANCH_NAME}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Step
        run: yarn setup

      - name: Run Lint
        run: yarn eslint

      - name: Run Test
        run: yarn test
