name: CI

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set branch name
        run: echo >>$GITHUB_ENV BRANCH_NAME=${GITHUB_REF#refs/heads/}
      
      - name: Echo branch name
        run: echo ${BRANCH_NAME}
      
      - name: Setup Node
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm run setup
      
      - name: Build Packages
        run: npm run build

      - name: Run Lint
        run: npm run eslint

      - name: Run Test
        run: npm run test
      