name: CI

on: [push]

jobs:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [14.x]
  main:
    steps:
      - uses: actions/checkout@v2
      - name: Set branch name
        run: echo >>$GITHUB_ENV BRANCH_NAME=${GITHUB_REF#refs/heads/}
      - name: Echo branch name
        run: echo ${BRANCH_NAME}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: npm run setup
      - name: Build Packages
        run: npm run build
      - name: Run Lint
        run: npm run eslint
      - name: Run Test
        run: npm run test
      